import Layout from '@/components/global/Layout';

import fonts from './fonts';
import Providers from './providers';

import 'src/styles/normalize.css';
import 'src/styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={fonts.miSaeng}>
      <body>
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
