name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  DEFAULT_NODE_VERSION: "16.19.1"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn lint

      - name: Check Unit Test
        run: yarn test:coverage

      # - name: Set unit test coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
